### PR TITLE
Fix reversed upTown and downTown arrival filtering

### LINKED ISSUE #63: [🐛 BUG] - upTown and downTown configuration values reversed
**Describe the bug**
The `upTown` and `downTown` settings seem to have the inverse effect when applied separately. That is, setting `upTown` to `true` and `downTown` to `false` leads to only "downtown" or outbound trains being displayed, and vice versa.

**To Reproduce**
1. Set `upTown` to `true` and `downTown` to `false` in the module configuration
2. Start MagicMirror with an instance of MMM-nyc-transit configured
3. Compare with MTA real-time data from mta.info

**Expected behavior**
Filtering for only "uptown" trains should lead to only uptown trains being displayed.

** Actual behavior**
Only "downtown" trains are displayed; uptown trains are not displayed.

**Configuration**
```
        {
            module: 'MMM-nyc-transit',
            position: "top_left",
            header: "9 Av",
            config: {
                apiKey: '...',
                displayType: 'list',
                mtaType: 'train',
                stations: [
                    {
                        stationId: 59,
                        walkingTime: 0,
                        dir: {
                            upTown: true,
                            downTown: false
                        }
                    }
                ],
                fadeSpeed: 0
            }
        },
```

### PR DESCRIPTION
**Pull request by joolean**
Resolves #63.

### CODE REVIEW

**Comment by Elaniobro** [comment]
Thank you for the PR @joolean; been swamped with work but will look at this tonight. I want to verify the 🐛

**Comment by joolean** [comment]
Hey @Elaniobro! Have you had a chance to reproduce the issue?

**Review by Elaniobro — APPROVED** [review]
Aye, @joolean thank you again for the assist. :shipit: 📦 

Please continue to contribute. 👍

**Comment by Elaniobro** [comment]
@all-contributors please add @joolean for bug code

**Pull request merged**
